name: 'ZAP Scan'
description: 'Scans the web application with ZAP'
inputs:
  workspace:
    description: 'workspace of the project'
    required: true
  token:
    description: 'Github Token'
    required: true
    default: '1000'
  branch:
    description: 'branch of the repo'
    required: true
    default: 'master'
  zap_work_dir:
    description: 'zap working directory'
    required: true
    default: './zap'
  repo_name:
    description: 'Git repo name ownerName/repoName'
    required: true
  report_name:
    description: 'Name of the report to be generated'
    required: true
    default: 'report_json.json'

outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
