on:
  push:
    paths-ignore:
      - '.zap/**'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ZAP Scan
        uses: ./
        with:
          workspace: ${{ github.workspace }}
          token: ${{ secrets.GIT_TOKEN }}
          repo_name: ${{github.repository}}
          zap_work_dir: '.zap'
          branch: 'master'
          report_name: 'report_md.md'
          zap_conf_file_name: 'zap.yaml'
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.zaproxy.org/'
          rules_file_name: 'rules.tsv'
      - uses: actions/upload-artifact@v1
        with:
          name: report
          path: ${{ github.workspace }}/index.js
